# Generated by Django 3.0 on 2020-10-19 11:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Activity name   ')),
                ('definition', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Activity description ')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Process title  ')),
                ('definition', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Task title   ')),
                ('definition', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('activety_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_process', to='classroom.Activity', verbose_name='Activity Name  ')),
            ],
        ),
        migrations.CreateModel(
            name='Type_actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Type actor title :  ')),
                ('definition', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologie_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Technoly :  ')),
                ('definition', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('technology_maturity', models.CharField(blank=True, max_length=270, null=True, verbose_name="Technology's maturity :  ")),
                ('task_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_process', to='classroom.Task', verbose_name='Task ')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Skill title:  ')),
                ('skills_maturity', models.CharField(blank=True, max_length=270, null=True, verbose_name='Skill maturity :  ')),
                ('definition', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('task_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_process', to='classroom.Task', verbose_name='Task  ')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Output title ')),
                ('definition', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('task_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_process', to='classroom.Task', verbose_name='Task Output ')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Input   ')),
                ('definition', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('task_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ressource_process', to='classroom.Task', verbose_name='Task Input ')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Decision title   ')),
                ('definition', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('task_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_process', to='classroom.Task', verbose_name='Task Decision ')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='First Name  ')),
                ('prenom', models.CharField(blank=True, max_length=270, null=True, verbose_name='Last Name  ')),
                ('presentation', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('adress', models.CharField(blank=True, max_length=270, null=True, verbose_name='Adress  ')),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Contact', max_length=31, null=True)),
                ('partenair_nam1', models.CharField(blank=True, max_length=270, null=True, verbose_name='Partner ')),
                ('partenair_nam2', models.CharField(blank=True, max_length=270, null=True, verbose_name='Partner ')),
                ('partenair_nam3', models.CharField(blank=True, max_length=270, null=True, verbose_name='Partner  ')),
                ('partenair_nam4', models.CharField(blank=True, max_length=270, null=True, verbose_name='Partner  ')),
                ('type_actor', models.CharField(blank=True, help_text=' help text.', max_length=270, null=True, verbose_name='Type of actor  ')),
                ('task_id', models.ManyToManyField(blank=True, help_text=' help text.', related_name='actor_process', to='classroom.Task', verbose_name='Actor_proces  ')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='process_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_process', to='classroom.Process', verbose_name='Select a Process :'),
        ),
    ]
